version: '3.9'

services:
  app:
    image: lern-it
    ports:
      - "${BACKEND_EXTERNAL_PORT}:${BACKEND_EXTERNAL_PORT}"
    command: ["bundle", "exec", "rails", "s", "-p", "$BACKEND_EXTERNAL_PORT", "-b", "0.0.0.1"]
    container_name: lern-it
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    container_name: lern-it-db
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      # NOTE: these values exist only on development at the moment - left hardcoded then
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - ./.env
volumes:
  postgres-data: