name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DATABASE_NAME: lern_it_test
  DATABASE_HOST: localhost
  DATABASE_USER: postgres
  DATABASE_PASSWORD: postgres
  RUBY_VERSION: 3.1.2
  DEVISE_JWT_SECRET_KEY: ${{ secrets.devise_jwt_secret_key }}

jobs:
  tests:
    name: RSpec tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports:
          - "5432:5432"
        env:
          POSTGRES_HOST: ${{ env.DATABASE_HOST }}
          POSTGRES_USER: ${{ env.DATABASE_USER }}
          POSTGRES_DB: ${{ env.DATABASE_NAME }}
          POSTGRES_PASSWORD: ${{ env.DATABASE_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RAILS_ENV: test
      #DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ env.RUBY_VERSION }}


      - name: Set up database schema
        run: bundle exec rails db:prepare


      - name: Run tests
        run: bundle exec rspec .

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          bundler-cache: true
      # Add or replace any other lints here
      #- name: Security audit dependencies
      #   run: bin/bundler-audit --update
      - name: Security audit application code
        run: bin/brakeman -q -w2

      - name: Rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          reek_version: gemfile
          fail_on_error: true

      - name: Reek
        uses: reviewdog/action-reek@v1
        with:
          reek_version: gemfile
          fail_on_error: true